layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 30
  exclude:
    forks: false
    projects:
     - first-contributions
     
social_media:
  # behance: your_username
  # dribbble: your_username
  website: http://www.aviralverma.com
  facebook: aviraliitk
  # hackerrank: your_username
  instagram: aviral_verma_official
  # keybase: your_username
  linkedin: aviraliitk
  medium: aviralverma
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # youtube: your_username

topics:
  - name: Angular
    web_url: https://angular.io/
    image_url: assets/images/angular.svg

  - name: React
    web_url: https://reactjs.org/
    image_url: assets/images/react.svg


  - name: Sass
    web_url: https://github.com/topics/sass
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
